# .github/workflows/build-and-test.yml
name: Build and Test
on:
  push: 
    branches:
      - main
  pull_request:
jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: npm
      - name: Install dependencies
        run: npm install
      - name: Run unit tests
        run: npm test
      - name: Run app
        run: npm run start &
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.7.0
        env:
          ZAP_AUTH_HEADER: 'Cookie'
          ZAP_AUTH_HEADER_VALUE: 'idp_marker=0e55251f-3422-467b-b644-9bfb13973870; sncc=P=67:V=4.0.0&C=C01,C02&D=true; _ga=GA1.2.1262097418.1686148764; _gid=GA1.2.1456373384.1686148764; _hjFirstSeen=1; _hjSession_3298197=eyJpZCI6IjUyNjBhMDA4LTExNGItNGRlZS1iOTM1LTk2MWVlNjY5YTZlNCIsImNyZWF0ZWQiOjE2ODYxNDg4OTc0MjksImluU2FtcGxlIjp0cnVlfQ==; _hjAbsoluteSessionInProgress=0; _hjSessionUser_3298197=eyJpZCI6IjU4NzEzMDU3LTkzNDAtNTk5ZS1hNWE2LTdhNzY3MjFlMTBhYyIsImNyZWF0ZWQiOjE2ODYxNDg4OTc0MjQsImV4aXN0aW5nIjp0cnVlfQ==; _gat_gtag_UA_64768501_1=1; idp_session=sVERSION_12bb60bd6-94be-4584-9735-fa088889fa17; idp_session_http=hVERSION_1f19912d2-5cf8-48a2-ab6d-ebc01ce5bd95'
        with:
          target: 'https://librarian.springernature.com/'
          
